### PR TITLE
Make Element.attributes iterable

### PR DESCRIPTION
**Pull request by jdanyow**
enables:
```ts
for (const attribute of el.attributes) {
```

### CODE REVIEW

**Comment by jdanyow** [comment]
@harrishancock will this ship in the next release?

**Comment by jdanyow** [comment]
My bad, I don't think my change is quite right:
```diff
-  readonly attributes: Iterator<{ name: string; value: string }>;
+  readonly attributes: IterableIterator<{ name: string; value: string }>; // <--- my current change
+  readonly attributes: IterableIterator<[string, string]>; // <--- what the runtime actually exposes
```

**Comment by jdanyow** [comment]
updated to match docs:
https://developers.cloudflare.com/workers/reference/apis/html-rewriter/#properties:~:text=attributes%3A%20Iterator%20returns%20a%20%5Bname%2C%20value%5D,tag's%20attributes.%20This%20property%20is%20read%2Donly.

**Comment by harrishancock** [comment]
I'm not sure if the asymmetry with the DOM's API is intentional or not. (/cc @inikulin) It's a little unfortunate, but workers-types should just match what the runtime does and is documented to do, since changing the behavior, if we choose to do so, would take some time.

As for when this can be released, I defer to @ispivey!

**Comment by jdanyow** [comment]
@harrishancock @inikulin sounds good- PR matches the docs and workers runtime now. 

There's another small divergence from the DOM API with respect to Element.tagName. In the DOM it's always uppercase and in workers it's lowercase. May be worth calling these out in the docs.

**Comment by inikulin** [comment]
Back end returns an [object that exposes two getters](https://github.com/cloudflare/lol-html/blob/master/c-api/include/lol_html.h#L505) mimicking DOM API. So, the change will be required in Workers runtime only.

**Comment by jdanyow** [comment]
@harrishancock @ispivey I think this is ok to merge. The PR matches the Cloudflare workers runtime as it is today, fixing a bug in the type definitions that prevents writing valid code like this:

```js
rewriter.on('bla', {
  element: element => {
    for (const [name, value] of element.attributes) {  <-----
```

**Pull request merged**
